# Github Default
# highlighter: pygments
# github: [Repository metadata]

# Github Configuration Overrides
# safe: true
# lsi: false
# source: your top-level directory

##################################################
#                             GLOBAL CONFIGURATION
##################################################
## Time Zone
# Set the time zone for site generation. This sets the TZ environment variable,
# which Ruby uses to handle time and date creation and manipulation.
# Any entry from the IANA Time Zone Database is valid, e.g. America/New_York.
# A list of all available values can be found here. The default is the
# local time zone, as set by your operating system.
timezone: Asia/Shanghai

## Encoding
encoding: utf-8

## Exclude
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
##################################################
#                            SERVE COMMAND OPTIONS
##################################################
## Base URL
baseurl: "" # the subpath of your site, e.g. /blog/


# Site settings

title: Bingqing Qu

email: sylar.qu@gmail.com

description: > # this means to ignore newlines until "baseurl:"
    A Machine Learner.




url: "http://jetpie.github.io" # the base hostname & protocol for your site

twitter_username:
github_username:  jetpie

# Build settings
markdown: kramdown